variables:
  - name: ENV
    value: uat
  - name: azureSubscription
    value: "TODO_AZURE_SERVICE_CONNECTION"
  - name: appServiceName
    value: "TODO_UAT_APP_SERVICE_NAME"
  - name: resourceGroup
    value: "TODO_UAT_RESOURCE_GROUP"
